-- Your SQL goes here
-- Auth & RBAC

-- Enable pgcrypto for gen_random_uuid()
CREATE EXTENSION IF NOT EXISTS "pgcrypto";

CREATE TABLE tbl_user_account (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY (START 1000) PRIMARY KEY,
    user_id VARCHAR(120) NOT NULL,
    employee_id BIGINT REFERENCES tbl_employee(id) ON DELETE SET NULL,
    username VARCHAR(128) UNIQUE NOT NULL,
    password_hash VARCHAR(128),
    pass_salt UUID NOT NULL DEFAULT gen_random_uuid(),
    token_salt UUID NOT NULL DEFAULT gen_random_uuid(),
    status TEXT DEFAULT 'Active',

    -- Timestamps
    cid BIGINT NOT NULL,
    ctime TIMESTAMP WITH TIME ZONE NOT NULL,
    mid BIGINT NOT NULL,
    mtime TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE tbl_role (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY (START 1000) PRIMARY KEY,
    name TEXT NOT NULL UNIQUE,
    description TEXT,
    
    -- Timestamps
    cid BIGINT NOT NULL,
    ctime TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE tbl_permission (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY (START 1000) PRIMARY KEY,
    module TEXT NOT NULL,
    action TEXT NOT NULL,
    level TEXT,

    -- Timestamps
    cid BIGINT NOT NULL,
    ctime TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE tbl_user_role (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY (START 1000) PRIMARY KEY,
    user_id BIGINT REFERENCES tbl_user_account(id) ON DELETE CASCADE,
    role_id BIGINT REFERENCES tbl_role(id) ON DELETE CASCADE,

    -- Timestamps
    cid BIGINT NOT NULL,
    ctime TIMESTAMP WITH TIME ZONE NOT NULL,
    mid BIGINT NOT NULL,
    mtime TIMESTAMP WITH TIME ZONE NOT NULL,
    UNIQUE(user_id, role_id)
);

CREATE TABLE tbl_role_permission (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY (START 1000) PRIMARY KEY,
    role_id BIGINT REFERENCES tbl_role(id) ON DELETE CASCADE,
    permission_id BIGINT REFERENCES tbl_permission(id) ON DELETE CASCADE,

    -- Timestamps
    cid BIGINT NOT NULL,
    ctime TIMESTAMP WITH TIME ZONE NOT NULL,
    mid BIGINT NOT NULL,
    mtime TIMESTAMP WITH TIME ZONE NOT NULL,
    UNIQUE(role_id, permission_id)
);

/* Index */

-- tbl_user_account
-- Lookup by UUID
CREATE INDEX idx_user_account_uuid ON tbl_user_account(user_id);

-- Login queries (username → user record)
CREATE INDEX idx_user_account_username ON tbl_user_account(username);

-- Filtering by employee → user mapping
CREATE INDEX idx_user_account_employee_id ON tbl_user_account(employee_id);

-- Filtering by account status (Active, Disabled, Locked, etc.)
CREATE INDEX idx_user_account_status ON tbl_user_account(status);

-- Password and token salts are not indexed for security reasons.

-- tbl_role
CREATE INDEX idx_role_name ON tbl_role(name);

-- tbl_permission
-- Find permissions by module (example: Payroll, Leaves, Attendance)
CREATE INDEX idx_permission_module ON tbl_permission(module);

-- Most RBAC systems check module + action
CREATE INDEX idx_permission_module_action ON tbl_permission(module, action);

-- tbl_user_role
-- FK lookups
CREATE INDEX idx_user_role_user ON tbl_user_role(user_id);
CREATE INDEX idx_user_role_role ON tbl_user_role(role_id);

-- Unique constraint already exists:
-- UNIQUE(user_id, role_id)
-- Optional index composite for fast "who has, which role" dashboards;
CREATE INDEX idx_user_role_role_user ON tbl_user_role(role_id, user_id);

-- tbl_role_permission
CREATE INDEX idx_role_perm_perm_role ON tbl_role_permission(permission_id, role_id);

/* For security / performance tweaks */

-- When often checking permissions for roles
CREATE INDEX idx_role_permission_lookup ON tbl_role_permission(role_id, permission_id);

-- For login-specific filtered index
CREATE INDEX idx_user_account_active_only ON tbl_user_account(username) WHERE status = 'Active';

-- Enforce permission uniqueness
ALTER TABLE tbl_permission ADD CONSTRAINT unique_permission UNIQUE(module, action);

