[package]
name = "lib-models"
version.workspace = true
edition.workspace = true
description.workspace = true
authors.workspace = true

[dependencies]
chrono.workspace = true
derive_more.workspace = true
enum_dispatch = "0.3.13"
modql.workspace = true
sea-query.workspace = true
serde.workspace = true
serde_json.workspace = true
serde_with.workspace = true
sqlx.workspace = true
uuid.workspace = true

[lints]
workspace = true
