[package]
name = "lib-models"
version.workspace = true
edition.workspace = true
description.workspace = true
authors.workspace = true

[dependencies]
chrono.workspace = true
diesel = { workspace = true, features = ["postgres", "time", "uuid"] }
serde = "1.0.228"
serde_json.workspace = true
serde_with.workspace = true

[lints]
workspace = true
