-- Add up migration script here
-- Your SQL goes here

/*-- Master tables*/
CREATE TABLE IF NOT EXISTS tbl_department (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY (START 1000) PRIMARY KEY,
    department_id UUID NOT NULL DEFAULT gen_random_uuid(),
    name TEXT NOT NULL UNIQUE,
    full_address TEXT NOT NULL,
    description TEXT,

    -- Timestamps
    cid BIGINT NOT NULL DEFAULT 0,
    ctime TIMESTAMP WITH TIME ZONE NOT NULL,
    mid BIGINT NOT NULL DEFAULT 0,
    mtime TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE IF NOT EXISTS tbl_salary_grade (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY (START 1000) PRIMARY KEY,
    salary_grade_id UUID NOT NULL DEFAULT gen_random_uuid(),
    level TEXT NOT NULL UNIQUE,
    base_salary NUMERIC(12,2) NOT NULL CHECK (base_salary >= 0),

    -- Timestamps
    cid BIGINT NOT NULL DEFAULT 0,
    ctime TIMESTAMP WITH TIME ZONE NOT NULL,
    mid BIGINT NOT NULL DEFAULT 0,
    mtime TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE IF NOT EXISTS tbl_job_position (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY (START 1000) PRIMARY KEY,
    job_position_id UUID NOT NULL DEFAULT gen_random_uuid(),
    title TEXT NOT NULL UNIQUE,
    department_id BIGINT NOT NULL REFERENCES tbl_department(id) ON UPDATE CASCADE,
    salary_grade_id BIGINT NOT NULL REFERENCES tbl_salary_grade(id) ON UPDATE CASCADE,
    description TEXT,

    -- Timestamps
    cid BIGINT NOT NULL DEFAULT 0,
    ctime TIMESTAMP WITH TIME ZONE NOT NULL,
    mid BIGINT NOT NULL DEFAULT 0,
    mtime TIMESTAMP WITH TIME ZONE NOT NULL
);

-- Address (1:1)
CREATE TABLE IF NOT EXISTS tbl_address (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY (START 1000) PRIMARY KEY,
    address_id UUID NOT NULL DEFAULT gen_random_uuid(),
    building_number TEXT NOT NULL,
    purok_name TEXT NOT NULL,
    street_name TEXT NOT NULL,
    barangay TEXT NOT NULL,
    city TEXT NOT NULL,
    municipality TEXT NOT NULL,
    province TEXT NOT NULL,
    zipcode SMALLINT NOT NULL,

    -- Timestamps
    cid BIGINT NOT NULL DEFAULT 0,
    ctime TIMESTAMP WITH TIME ZONE NOT NULL,
    mid BIGINT NOT NULL DEFAULT 0,
    mtime TIMESTAMP WITH TIME ZONE NOT NULL
);

-- Employee
CREATE TABLE IF NOT EXISTS tbl_employee (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY (START 1000) PRIMARY KEY,
    employee_id UUID NOT NULL DEFAULT gen_random_uuid(),
    firstname VARCHAR(120) NOT NULL,
    middlename TEXT,
    lastname VARCHAR(120) NOT NULL,
    hire_date DATE NOT NULL,
    status user_session_state NOT NULL DEFAULT 'active',
    supervisor_id BIGINT REFERENCES tbl_employee(id) ON DELETE SET NULL ON UPDATE CASCADE,
    address_id BIGINT UNIQUE REFERENCES tbl_address(id) ON DELETE SET NULL,
    department_id BIGINT REFERENCES tbl_department(id) ON DELETE SET NULL,
    job_position_id BIGINT REFERENCES tbl_job_position(id) ON DELETE SET NULL,

    -- Timestamps
    cid BIGINT NOT NULL DEFAULT 0,
    ctime TIMESTAMP WITH TIME ZONE NOT NULL,
    mid BIGINT NOT NULL DEFAULT 0,
    mtime TIMESTAMP WITH TIME ZONE NOT NULL
);

-- Emergency Contact
CREATE TABLE IF NOT EXISTS tbl_emergency_contact (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY (START 1000) PRIMARY KEY,
    emergency_contact_id UUID NOT NULL DEFAULT gen_random_uuid()),
    firstname VARCHAR(120) NOT NULL,
    lastname VARCHAR(120) NOT NULL,
    phone_number TEXT NOT NULL,
    full_address TEXT NOT NULL,

    -- Timestamps
    cid BIGINT NOT NULL DEFAULT 0,
    ctime TIMESTAMP WITH TIME ZONE NOT NULL,
    mid BIGINT NOT NULL DEFAULT 0,
    mtime TIMESTAMP WITH TIME ZONE NOT NULL
);
-- Time & Attendance
CREATE TABLE IF NOT EXISTS tbl_time_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY (START 1000) PRIMARY KEY,
    time_log_id UUID NOT NULL DEFAULT gen_random_uuid(),
    employee_id BIGINT NOT NULL REFERENCES tbl_employee(id) ON DELETE CASCADE,
    check_in TIMESTAMP NOT NULL,
    check_out TIMESTAMP,
    notes TEXT,
    CHECK (check_out IS NULL OR check_out >= check_in),
    
    -- Timestamps
    cid BIGINT NOT NULL DEFAULT 0,
    ctime TIMESTAMP WITH TIME ZONE NOT NULL,
    mid BIGINT NOT NULL DEFAULT 0,
    mtime TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE IF NOT EXISTS tbl_attendance_record (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY (START 1000) PRIMARY KEY,
    attendance_record_id UUID NOT NULL DEFAULT gen_random_uuid(),
    employee_id BIGINT NOT NULL REFERENCES tbl_employee(id) ON DELETE CASCADE,
    date DATE NOT NULL,
    status attendance_status NOT NULL DEFAULT 'field_work',
    
    -- Timestamps
    cid BIGINT NOT NULL DEFAULT 0,
    ctime TIMESTAMP WITH TIME ZONE NOT NULL,
    mid BIGINT NOT NULL DEFAULT 0,
    mtime TIMESTAMP WITH TIME ZONE NOT NULL
);

-- Leave
CREATE TABLE IF NOT EXISTS tbl_leave_type (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY (START 1000) PRIMARY KEY,
    leave_type_id UUID NOT NULL DEFAULT gen_random_uuid(),
    name TEXT NOT NULL UNIQUE,
    max_days INT CHECK (max_days >= 0),
    is_paid BOOLEAN DEFAULT TRUE,
    
    -- Timestamps
    cid BIGINT NOT NULL DEFAULT 0,
    ctime TIMESTAMP WITH TIME ZONE NOT NULL,
    mid BIGINT NOT NULL DEFAULT 0,
    mtime TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE IF NOT EXISTS tbl_leave_balance (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY (START 1000) PRIMARY KEY,
    employee_id BIGINT NOT NULL REFERENCES tbl_employee(id) ON DELETE CASCADE,
    leave_type_id BIGINT NOT NULL REFERENCES tbl_leave_type(id) ON DELETE CASCADE,
    balance_days INT NOT NULL CHECK (balance_days >= 0),
    
    -- Timestamps
    cid BIGINT NOT NULL DEFAULT 0,
    ctime TIMESTAMP WITH TIME ZONE NOT NULL,
    mid BIGINT NOT NULL DEFAULT 0,
    mtime TIMESTAMP WITH TIME ZONE NOT NULL,

    UNIQUE(employee_id, leave_type_id)
);

CREATE TABLE IF NOT EXISTS tbl_leave_request (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY (START 1000) PRIMARY KEY,
    employee_id BIGINT NOT NULL REFERENCES tbl_employee(id) ON DELETE CASCADE,
    leave_type_id BIGINT NOT NULL REFERENCES tbl_leave_type(id),
    start_date DATE NOT NULL,
    end_date DATE NOT NULL,
    reason TEXT,
    status leave_request_status NOT NULL DEFAULT 'pending',
    created_at TIMESTAMP DEFAULT NOW(),
    updated_at TIMESTAMP DEFAULT NOW(),
    
    -- Timestamps
    cid BIGINT NOT NULL DEFAULT 0,
    ctime TIMESTAMP WITH TIME ZONE NOT NULL,
    mid BIGINT NOT NULL DEFAULT 0,
    mtime TIMESTAMP WITH TIME ZONE NOT NULL,

    CHECK (end_date >= start_date)
);

-- Payroll
CREATE TABLE IF NOT EXISTS tbl_earning (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY (START 1000) PRIMARY KEY,
    earning_id UUID NOT NULL DEFAULT gen_random_uuid(),
    name VARCHAR(120) NOT NULL,
    amount NUMERIC(12,2) NOT NULL CHECK (amount >= 0),
    taxable BOOLEAN DEFAULT TRUE,
    
    -- Timestamps
    cid BIGINT NOT NULL DEFAULT 0,
    ctime TIMESTAMP WITH TIME ZONE NOT NULL,
    mid BIGINT NOT NULL DEFAULT 0,
    mtime TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE IF NOT EXISTS tbl_deduction (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY (START 1000) PRIMARY KEY,
    deduction_id UUID NOT NULL DEFAULT gen_random_uuid(),
    name VARCHAR(120) NOT NULL,
    amount NUMERIC(12,2) CHECK (amount >= 0),
    percentage NUMERIC(5,2) CHECK (percentage >= 0),
    
    -- Timestamps
    cid BIGINT NOT NULL DEFAULT 0,
    ctime TIMESTAMP WITH TIME ZONE NOT NULL,
    mid BIGINT NOT NULL DEFAULT 0,
    mtime TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE IF NOT EXISTS tbl_kpi (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY (START 1000) PRIMARY KEY,
    kpi_id UUID NOT NULL DEFAULT gen_random_uuid(),
    name VARCHAR(120) NOT NULL,
    weight INT CHECK (weight >= 0),
    
    -- Timestamps
    cid BIGINT NOT NULL DEFAULT 0,
    ctime TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    mid BIGINT NOT NULL DEFAULT 0,
    mtime TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS tbl_payroll (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY (START 1000) PRIMARY KEY,
    employee_id BIGINT NOT NULL REFERENCES tbl_employee(id) ON DELETE CASCADE,
    start_period DATE NOT NULL,
    end_period DATE NOT NULL,
    gross_pay NUMERIC(12,2) NOT NULL CHECK (gross_pay >= 0),
    total_deductions NUMERIC(12,2) CHECK (total_deductions >= 0) DEFAULT 0,
    net_pay NUMERIC(12,2) NOT NULL CHECK (net_pay >= 0),
    date_processed TIMESTAMP DEFAULT NOW(),
    
    -- Timestamps
    cid BIGINT NOT NULL DEFAULT 0,
    ctime TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    mid BIGINT NOT NULL DEFAULT 0,
    mtime TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),

    CHECK (end_period >= start_period)
);

CREATE TABLE IF NOT EXISTS tbl_performance_review (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY (START 1000) PRIMARY KEY,
    employee_id BIGINT NOT NULL REFERENCES tbl_employee(id),
    date_evaluated DATE NOT NULL,
    score INT CHECK (score BETWEEN 0 AND 100),
    remarks TEXT,
    status performance_review_status,
    
    -- Timestamps
    cid BIGINT NOT NULL DEFAULT 0,
    ctime TIMESTAMP WITH TIME ZONE NOT NULL,
    mid BIGINT NOT NULL DEFAULT 0,
    mtime TIMESTAMP WITH TIME ZONE NOT NULL
);

/* Indexes */

-- tbl_department
CREATE INDEX idx_department_uuid ON tbl_department(department_id);
CREATE INDEX idx_department_name ON tbl_department(name);

-- tbl_salary_grade
CREATE INDEX idx_salary_grade_uuid ON tbl_salary_grade(salary_grade_id);
CREATE INDEX idx_salary_grade_level ON tbl_salary_grade(level);

-- tbl_job_position
CREATE INDEX idx_job_position_uuid ON tbl_job_position(job_position_id);
CREATE INDEX idx_job_position_department ON tbl_job_position(department_id);
CREATE INDEX idx_job_position_salary_grade ON tbl_job_position(salary_grade_id);
CREATE INDEX idx_job_position_title ON tbl_job_position(title);

-- tbl_address
CREATE INDEX idx_address_uuid ON tbl_address(address_id);
CREATE INDEX idx_address_location ON tbl_address(city, province);

-- tbl_employee
CREATE INDEX idx_employee_uuid ON tbl_employee(employee_id);
CREATE INDEX idx_employee_name ON tbl_employee(lastname, firstname, middlename);
CREATE INDEX idx_employee_department ON tbl_employee(department_id);
CREATE INDEX idx_employee_job_position ON tbl_employee(job_position_id);
CREATE INDEX idx_employee_supervisor ON tbl_employee(supervisor_id);
CREATE INDEX idx_employee_status ON tbl_employee(status);
CREATE INDEX idx_employee_hire_date ON tbl_employee(hire_date);

-- tbl_emergency_contact
CREATE INDEX idx_emergency_contact_uuid ON tbl_emergency_contact(emergency_contact_id);
CREATE INDEX idx_emergency_contact_name ON tbl_emergency_contact(firstname, lastname);
CREATE INDEX idx_phone_number ON tbl_emergency_contact(phone_number);

-- tbl_time_log
CREATE INDEX idx_time_log_uuid ON tbl_time_log(time_log_id);
CREATE INDEX idx_time_log_employee ON tbl_time_log(employee_id);
CREATE INDEX idx_time_log_checkin ON tbl_time_log(check_in);
CREATE INDEX idx_time_log_checkout ON tbl_time_log(check_out);
CREATE INDEX idx_time_log_employee_date ON tbl_time_log(employee_id, check_in);

-- tbl_attendance_record
CREATE INDEX idx_attendance_uuid ON tbl_attendance_record(attendance_record_id);
CREATE INDEX idx_attendance_employee ON tbl_attendance_record(employee_id);
CREATE INDEX idx_attendance_date ON tbl_attendance_record(date);
CREATE INDEX idx_attendance_status ON tbl_attendance_record(status);
CREATE UNIQUE INDEX idx_attendance_employee_date ON tbl_attendance_record(employee_id, date);

-- tbl_leave_type
CREATE INDEX idx_leave_type_uuid ON tbl_leave_type(leave_type_id);
CREATE INDEX idx_leave_type_name ON tbl_leave_type(name);

-- tbl_leave_balance
CREATE INDEX idx_leave_balance_employee ON tbl_leave_balance(employee_id);
CREATE INDEX idx_leave_balance_type ON tbl_leave_balance(leave_type_id);
CREATE UNIQUE INDEX idx_leave_balance_unique ON tbl_leave_balance(employee_id, leave_type_id);

-- tbl_leave_request
CREATE INDEX idx_leave_request_employee ON tbl_leave_request(employee_id);
CREATE INDEX idx_leave_request_type ON tbl_leave_request(leave_type_id);
CREATE INDEX idx_leave_request_status ON tbl_leave_request(status);
CREATE INDEX idx_leave_request_dates ON tbl_leave_request(start_date, end_date);
CREATE INDEX idx_leave_request_created_at ON tbl_leave_request(created_at);

-- tbl_earning
CREATE INDEX idx_earning_uuid ON tbl_earning(earning_id);
CREATE INDEX idx_earning_name ON tbl_earning(name);

-- tbl_deduction
CREATE INDEX idx_deduction_uuid ON tbl_deduction(deduction_id);
CREATE INDEX idx_deduction_name ON tbl_deduction(name);

-- tbl_kpi
CREATE INDEX idx_kpi_uuid ON tbl_kpi(kpi_id);
CREATE INDEX idx_kpi_name ON tbl_kpi(name);

-- tbl_payroll
CREATE INDEX idx_payroll_employee ON tbl_payroll(employee_id);
CREATE INDEX idx_payroll_period ON tbl_payroll(start_period, end_period);
CREATE INDEX idx_payroll_processed ON tbl_payroll(date_processed);

-- tbl_performance_review
CREATE INDEX idx_perf_review_employee ON tbl_performance_review(employee_id);
CREATE INDEX idx_perf_review_date ON tbl_performance_review(date_evaluated);
CREATE INDEX idx_perf_review_status ON tbl_performance_review(status);

