-- Add up migration script here
-- Your SQL goes here


CREATE TABLE tbl_applicant (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY (START 1000) PRIMARY KEY,

    full_name VARCHAR(150) NOT NULL,
    email VARCHAR(150) NOT NULL,
    status applicant_status NOT NULL DEFAULT 'applied',

    -- Timestamps
    cid BIGINT NOT NULL,
    ctime TIMESTAMP WITH TIME ZONE NOT NULL,
    mid BIGINT NOT NULL,
    mtime TIMESTAMP WITH TIME ZONE NOT NULL
);
