-- AUDIT LOG (Expanded Version)
CREATE TABLE tbl_audit_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY (START 1000) PRIMARY KEY,

    -- Who performed the action
    actor_id BIGINT REFERENCES tbl_user_account(id),
    actor_role TEXT,                           -- admin, hr_staff, payroll, system

    -- What event happened
    action TEXT NOT NULL,                      -- INSERT, UPDATE, DELETE, LOGIN, LOGOUT, etc.
    event_type TEXT NOT NULL,                  -- business category: employee_update, payroll_run, leave_approve, etc.
    severity TEXT NOT NULL DEFAULT 'info',     -- info | warning | critical

    -- Target of the action
    target_table TEXT NOT NULL,                -- tbl_employee, tbl_attendance, tbl_payroll
    target_id BIGINT,                          -- specific row ID
    target_summary TEXT,                       -- optional human-readable description (e.g. "Mario Santos – Employee Record")

    -- Change details
    old_values JSONB,                           -- before update
    new_values JSONB,                           -- after update
    diff JSONB,                                 -- only changed fields
    change_source TEXT DEFAULT 'app',           -- app | api | batch | system

    -- Request context
    ip_address INET,                            -- where request originated
    user_agent TEXT,                            -- browser / app / desktop info
    device_info JSONB,                          -- os, platform, device model
    trace_id TEXT,                              -- distributed tracing id
    session_id UUID,                            -- maps to active_sessions table

    -- Additional attachments
    metadata JSONB,                             -- additional contextual details (payroll cycle id, module name, etc.)

    -- Timestamps
    cid BIGINT NOT NULL,
    ctime TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    mid BIGINT NOT NULL,
    mtime TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);

/* Indexes */

CREATE INDEX idx_audit_target ON tbl_audit_log (target_table, target_id);
CREATE INDEX idx_audit_actor ON tbl_audit_log (actor_id);
CREATE INDEX idx_audit_event_type ON tbl_audit_log (event_type);
CREATE INDEX idx_audit_ctime ON tbl_audit_log (ctime);

