[cargo-new]
vcs = "none"

[env]
RUST_LOG="hiive=debug,reqwest_client=debug,lib_core=debug,lib_utils=debug,lib_auth=debug"

# -- Service Environment Variables
# IMPORTANT: 
#   For cargo commands only.
#   For deployed env, should be managed by container 
#   (e.g., Kubernetes).

## -- Secrets
# Keys and passwords below are for localhost dev ONLY.
# e.g., "welcome" type of passwords.
# i.e., Encryption not needed.

DATABASE_URL="postgres://devixion:Dev_only.2025@localhost/hiive_lume_db"
SERVICE_WEB_FOLDER = "public"

SERVICE_PWD_KEY="X6i9NNjv6SvF0oltbZVVvl-89drBwCRNp4whN3u6ZBALpxqoGCIpxXxkzI57rNQM79lG0A2EIC4UDTPeIZDZqA"

SERVICE_TOKEN_KEY="lQ9G0j7bVR3UW_HeFHWftGquev3Hb0K6pn2L3PBjx3inmDhR2KVCDbDjl1_d3lEM8fvjU_yCnZP408wjjlrSFg"
SERVICE_TOKEN_DURATION_SEC="1800" # 30 minutes

