[package]
name = "lib-core"
version.workspace = true
edition.workspace = true
description.workspace = true
authors.workspace = true

[lints]
workspace = true

[dependencies]
lib-auth = { version = "0.1.0", path = "../lib-auth" }
lib-utils = { version = "0.1.0", path = "../lib-utils" }

derive_more.workspace = true
modql.workspace = true
sea-query.workspace = true
sea-query-binder.workspace = true
serde.workspace = true
serde_json.workspace = true
serde_with.workspace = true
sqlx.workspace = true
time.workspace = true
tokio.workspace = true
tracing.workspace = true
uuid.workspace = true
diesel = { workspace = true, features = ["postgres", "time", "uuid", "chrono", "serde_json", "r2d2"] }
