[package]
name = "hiive"
version.workspace = true
edition.workspace = true

[dependencies]
anyhow.workspace = true
base64.workspace = true
chrono.workspace = true
gpui.workspace = true
gpui-component.workspace = true
gpui-component-assets.workspace = true
mockd.workspace = true
rand.workspace = true
rust-embed.workspace = true
serde_json.workspace = true
time.workspace = true
tokio.workspace = true
reqwest_client.workspace = true
tracing-subscriber = { version = "0.3.20", features = ["env-filter"] }
tracing = "0.1.41"
lib-utils = { version = "0.1.0", path = "../crates/lib-utils" }
lib-models = { version = "0.1.0", path = "../crates/lib-models" }

[[example]]
name = "example-001"
path = "examples/virtual_scroll.rs"

[[example]]
name = "example-002"
path = "examples/select_with_scroll.rs"

[[example]]
name = "gen-tool"
path = "examples/gen_tool.rs"
